language: csharp
solution: MessageMediaLookups.sln
install:
  - nuget restore MessageMediaLookups.sln
  - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MessageMediaLookups.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe ./MessageMediaLookups.Tests/bin/Release/MessageMediaLookups.Tests.dll
